# ruff: noqa: E501,I001,F401
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from sawyer.proto import sawyer_pb2 as sawyer_dot_proto_dot_sawyer__pb2

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in sawyer/proto/sawyer_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SawyerRouterStub:
    """──────────────────────────────────────────────
    Sawyer Distributed MoE Inference Protocol
    ──────────────────────────────────────────────

    ── Router Service (runs on the gateway) ──

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
            "/sawyer.SawyerRouter/RegisterNode",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.RegisterNodeRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.RegisterNodeResponse.FromString,
            _registered_method=True,
        )
        self.DeregisterNode = channel.unary_unary(
            "/sawyer.SawyerRouter/DeregisterNode",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.DeregisterNodeRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.DeregisterNodeResponse.FromString,
            _registered_method=True,
        )
        self.Heartbeat = channel.unary_unary(
            "/sawyer.SawyerRouter/Heartbeat",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )
        self.Infer = channel.unary_unary(
            "/sawyer.SawyerRouter/Infer",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.InferRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.InferResponse.FromString,
            _registered_method=True,
        )
        self.ListModels = channel.unary_unary(
            "/sawyer.SawyerRouter/ListModels",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.ListModelsRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.ListModelsResponse.FromString,
            _registered_method=True,
        )


class SawyerRouterServicer:
    """──────────────────────────────────────────────
    Sawyer Distributed MoE Inference Protocol
    ──────────────────────────────────────────────

    ── Router Service (runs on the gateway) ──

    """

    def RegisterNode(self, request, context):
        """Node registration and lifecycle"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeregisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Infer(self, request, context):
        """Inference"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListModels(self, request, context):
        """Model discovery"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SawyerRouterServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RegisterNode": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterNode,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.RegisterNodeRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.RegisterNodeResponse.SerializeToString,
        ),
        "DeregisterNode": grpc.unary_unary_rpc_method_handler(
            servicer.DeregisterNode,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.DeregisterNodeRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.DeregisterNodeResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.HeartbeatRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.HeartbeatResponse.SerializeToString,
        ),
        "Infer": grpc.unary_unary_rpc_method_handler(
            servicer.Infer,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.InferRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.InferResponse.SerializeToString,
        ),
        "ListModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListModels,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.ListModelsRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.ListModelsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sawyer.SawyerRouter", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("sawyer.SawyerRouter", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SawyerRouter:
    """──────────────────────────────────────────────
    Sawyer Distributed MoE Inference Protocol
    ──────────────────────────────────────────────

    ── Router Service (runs on the gateway) ──

    """

    @staticmethod
    def RegisterNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerRouter/RegisterNode",
            sawyer_dot_proto_dot_sawyer__pb2.RegisterNodeRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeregisterNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerRouter/DeregisterNode",
            sawyer_dot_proto_dot_sawyer__pb2.DeregisterNodeRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.DeregisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerRouter/Heartbeat",
            sawyer_dot_proto_dot_sawyer__pb2.HeartbeatRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Infer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerRouter/Infer",
            sawyer_dot_proto_dot_sawyer__pb2.InferRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerRouter/ListModels",
            sawyer_dot_proto_dot_sawyer__pb2.ListModelsRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class SawyerNodeStub:
    """── Node Service (runs on each volunteer node) ──"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadExpert = channel.unary_unary(
            "/sawyer.SawyerNode/LoadExpert",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.LoadExpertRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.LoadExpertResponse.FromString,
            _registered_method=True,
        )
        self.UnloadExpert = channel.unary_unary(
            "/sawyer.SawyerNode/UnloadExpert",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.UnloadExpertRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.UnloadExpertResponse.FromString,
            _registered_method=True,
        )
        self.ExpertInfer = channel.unary_unary(
            "/sawyer.SawyerNode/ExpertInfer",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.ExpertInferRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.ExpertInferResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/sawyer.SawyerNode/HealthCheck",
            request_serializer=sawyer_dot_proto_dot_sawyer__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=sawyer_dot_proto_dot_sawyer__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class SawyerNodeServicer:
    """── Node Service (runs on each volunteer node) ──"""

    def LoadExpert(self, request, context):
        """Router calls this to activate an expert on a node"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UnloadExpert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExpertInfer(self, request, context):
        """Router calls this to run inference on a loaded expert"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check from router to node"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SawyerNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "LoadExpert": grpc.unary_unary_rpc_method_handler(
            servicer.LoadExpert,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.LoadExpertRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.LoadExpertResponse.SerializeToString,
        ),
        "UnloadExpert": grpc.unary_unary_rpc_method_handler(
            servicer.UnloadExpert,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.UnloadExpertRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.UnloadExpertResponse.SerializeToString,
        ),
        "ExpertInfer": grpc.unary_unary_rpc_method_handler(
            servicer.ExpertInfer,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.ExpertInferRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.ExpertInferResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=sawyer_dot_proto_dot_sawyer__pb2.HealthCheckRequest.FromString,
            response_serializer=sawyer_dot_proto_dot_sawyer__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sawyer.SawyerNode", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("sawyer.SawyerNode", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SawyerNode:
    """── Node Service (runs on each volunteer node) ──"""

    @staticmethod
    def LoadExpert(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerNode/LoadExpert",
            sawyer_dot_proto_dot_sawyer__pb2.LoadExpertRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.LoadExpertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UnloadExpert(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerNode/UnloadExpert",
            sawyer_dot_proto_dot_sawyer__pb2.UnloadExpertRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.UnloadExpertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExpertInfer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerNode/ExpertInfer",
            sawyer_dot_proto_dot_sawyer__pb2.ExpertInferRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.ExpertInferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sawyer.SawyerNode/HealthCheck",
            sawyer_dot_proto_dot_sawyer__pb2.HealthCheckRequest.SerializeToString,
            sawyer_dot_proto_dot_sawyer__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
